import type { Section } from "./types";

export const indonesianTotalLabel = "~390 entries total · Built for conversational Bali Indonesian";

export const indonesianSections: Section[] = [
  {
    id: "verbs",
    title: "Common Verbs",
    count: "80 words",
    note: "Conversational Indonesian usually drops the me- prefix in speech. I've listed the base/informal form first, with the formal prefix in parentheses where relevant.",
    subsections: [
      {
        title: "Wanting, Feeling & Thinking",
        words: [
          { word: "mau", eng: "want / will (about to)", examples: [{ target: "Aku mau kopi.", eng: "I want coffee." }] },
          { word: "ingin", eng: "want / wish (slightly softer)", examples: [{ target: "Aku ingin belajar bahasa Indonesia.", eng: "I want to learn Indonesian." }] },
          { word: "suka", eng: "like", examples: [{ target: "Aku suka nasi goreng.", eng: "I like fried rice." }] },
          { word: "cinta", eng: "love", examples: [{ target: "Aku cinta Bali.", eng: "I love Bali." }] },
          { word: "sering", eng: "often (used verb-like: \"I often…\")", examples: [{ target: "Aku sering makan di sini.", eng: "I often eat here." }] },
          { word: "butuh", eng: "need", examples: [{ target: "Aku butuh air.", eng: "I need water." }] },
          { word: "perlu", eng: "need (slightly more formal)", examples: [{ target: "Kamu perlu istirahat.", eng: "You need to rest." }] },
          { word: "tahu", eng: "know (a fact)", examples: [{ target: "Aku nggak tahu.", eng: "I don't know." }] },
          { word: "kenal", eng: "know (a person) / be familiar with", examples: [{ target: "Kamu kenal dia?", eng: "Do you know him/her?" }] },
          { word: "pikir", eng: "think", examples: [{ target: "Aku pikir itu bagus.", eng: "I think that's good." }] },
          { word: "rasa", eng: "feel / sense / reckon", examples: [{ target: "Aku rasa dia nggak datang.", eng: "I reckon he's not coming." }] },
          { word: "ingat", eng: "remember", examples: [{ target: "Kamu ingat nama dia?", eng: "Do you remember his/her name?" }] },
          { word: "lupa", eng: "forget", examples: [{ target: "Aku lupa bawa dompet.", eng: "I forgot to bring my wallet." }] },
          { word: "ngerti / mengerti", eng: "understand", examples: [{ target: "Aku nggak ngerti.", eng: "I don't understand." }] },
          { word: "percaya", eng: "believe / trust", examples: [{ target: "Aku percaya kamu.", eng: "I trust you." }] },
          { word: "harap / berharap", eng: "hope", examples: [{ target: "Aku harap cuacanya bagus besok.", eng: "I hope the weather is good tomorrow." }] },
          { word: "takut", eng: "afraid / scared", examples: [{ target: "Aku takut sama ular.", eng: "I'm scared of snakes." }] },
          { word: "senang", eng: "happy / glad", examples: [{ target: "Aku senang ketemu kamu.", eng: "I'm glad to meet you." }] },
        ],
      },
      {
        title: "Doing & Moving",
        words: [
          { word: "pergi", eng: "go", examples: [{ target: "Mau pergi ke mana?", eng: "Where are you going?" }] },
          { word: "datang", eng: "come / arrive", examples: [{ target: "Dia datang dari Australia.", eng: "He/she comes from Australia." }] },
          { word: "pulang", eng: "go home / return home", examples: [{ target: "Aku mau pulang dulu.", eng: "I'm going to head home first." }] },
          { word: "balik", eng: "go back / return", tag: "casual", examples: [{ target: "Kapan kamu balik ke Bali?", eng: "When are you coming back to Bali?" }] },
          { word: "jalan", eng: "walk / go (casual)", examples: [{ target: "Ayo jalan-jalan!", eng: "Let's go for a walk / stroll around!" }] },
          { word: "lari", eng: "run", examples: [{ target: "Dia suka lari pagi.", eng: "He/she likes to run in the morning." }] },
          { word: "naik", eng: "go up / ride / get on", examples: [{ target: "Naik motor aja.", eng: "Just take the motorbike." }] },
          { word: "turun", eng: "go down / get off", examples: [{ target: "Turun di sini ya.", eng: "I'll get off here, okay." }] },
          { word: "sampai", eng: "arrive / until", examples: [{ target: "Sudah sampai belum?", eng: "Have you arrived yet?" }] },
          { word: "masuk", eng: "enter / go in", examples: [{ target: "Boleh masuk?", eng: "May I come in?" }] },
          { word: "keluar", eng: "go out / exit", examples: [{ target: "Aku mau keluar sebentar.", eng: "I want to go out for a bit." }] },
          { word: "tinggal", eng: "live / stay", examples: [{ target: "Kamu tinggal di mana?", eng: "Where do you live?" }] },
          { word: "pindah", eng: "move (to a new place)", examples: [{ target: "Aku baru pindah ke Canggu.", eng: "I just moved to Canggu." }] },
          { word: "bawa", eng: "bring / carry", examples: [{ target: "Jangan lupa bawa payung.", eng: "Don't forget to bring an umbrella." }] },
          { word: "ambil", eng: "take / pick up / fetch", examples: [{ target: "Aku ambil dulu di rumah.", eng: "I'll go pick it up at home first." }] },
          { word: "taruh / letakkan", eng: "put / place", examples: [{ target: "Taruh di sini aja.", eng: "Just put it here." }] },
          { word: "kirim", eng: "send", examples: [{ target: "Aku kirim lewat WhatsApp ya.", eng: "I'll send it via WhatsApp, okay." }] },
          { word: "terima", eng: "receive / accept", examples: [{ target: "Sudah terima pesannya?", eng: "Did you receive the message?" }] },
          { word: "cari", eng: "look for / search", examples: [{ target: "Aku lagi cari villa baru.", eng: "I'm looking for a new villa." }] },
          { word: "ketemu", eng: "meet / find (casual)", examples: [{ target: "Kapan kita bisa ketemu?", eng: "When can we meet?" }] },
          { word: "tunggu", eng: "wait", examples: [{ target: "Tunggu sebentar ya.", eng: "Wait a moment, okay." }] },
        ],
      },
      {
        title: "Daily Life",
        words: [
          { word: "makan", eng: "eat", examples: [{ target: "Sudah makan belum?", eng: "Have you eaten yet?" }] },
          { word: "minum", eng: "drink", examples: [{ target: "Mau minum apa?", eng: "What do you want to drink?" }] },
          { word: "tidur", eng: "sleep", examples: [{ target: "Aku tidur jam 11 tadi malam.", eng: "I slept at 11 last night." }] },
          { word: "bangun", eng: "wake up", examples: [{ target: "Aku bangun pagi-pagi sekali.", eng: "I woke up very early." }] },
          { word: "mandi", eng: "shower / bathe", examples: [{ target: "Aku mandi dulu ya.", eng: "I'll take a shower first, okay." }] },
          { word: "masak", eng: "cook", examples: [{ target: "Siapa yang masak hari ini?", eng: "Who's cooking today?" }] },
          { word: "pesan", eng: "order (food/drinks)", examples: [{ target: "Aku mau pesan nasi campur.", eng: "I want to order mixed rice." }] },
          { word: "bayar", eng: "pay", examples: [{ target: "Bayar di mana?", eng: "Where do I pay?" }] },
          { word: "beli", eng: "buy", examples: [{ target: "Aku beli ini di pasar.", eng: "I bought this at the market." }] },
          { word: "jual", eng: "sell", examples: [{ target: "Dia jual motor lamanya.", eng: "He/she sold the old motorbike." }] },
          { word: "sewa", eng: "rent", examples: [{ target: "Aku sewa motor per bulan.", eng: "I rent a motorbike monthly." }] },
          { word: "kerja", eng: "work", examples: [{ target: "Kamu kerja di mana?", eng: "Where do you work?" }] },
          { word: "istirahat", eng: "rest / take a break", examples: [{ target: "Kita istirahat dulu.", eng: "Let's take a break first." }] },
          { word: "latihan", eng: "practice / train", examples: [{ target: "Aku latihan handstand setiap hari.", eng: "I practice handstands every day." }] },
          { word: "olahraga", eng: "exercise / do sports", examples: [{ target: "Kamu suka olahraga apa?", eng: "What sports do you like?" }] },
        ],
      },
      {
        title: "Communication",
        words: [
          { word: "bilang", eng: "say / tell", tag: "casual", examples: [{ target: "Dia bilang nggak bisa datang.", eng: "He/she said they can't come." }] },
          { word: "ngomong", eng: "talk / speak", tag: "casual", examples: [{ target: "Ngomong apa sih?", eng: "What are you talking about?" }] },
          { word: "bicara", eng: "speak / talk (slightly more polite)", examples: [{ target: "Bisa bicara pelan-pelan?", eng: "Can you speak slowly?" }] },
          { word: "tanya", eng: "ask", examples: [{ target: "Boleh tanya?", eng: "May I ask?" }] },
          { word: "jawab", eng: "answer / reply", examples: [{ target: "Dia belum jawab chat aku.", eng: "He/she hasn't replied to my chat." }] },
          { word: "dengar", eng: "hear", examples: [{ target: "Kamu dengar nggak?", eng: "Did you hear that?" }] },
          { word: "lihat", eng: "see / look", examples: [{ target: "Lihat! Sunset-nya bagus banget.", eng: "Look! The sunset is really beautiful." }] },
          { word: "panggil", eng: "call (someone) / summon", examples: [{ target: "Panggil aku Vlad aja.", eng: "Just call me Vlad." }] },
          { word: "telepon", eng: "phone / call (on the phone)", examples: [{ target: "Aku telepon kamu nanti ya.", eng: "I'll call you later, okay." }] },
        ],
      },
      {
        title: "Actions & States",
        words: [
          { word: "bisa", eng: "can / able to", examples: [{ target: "Kamu bisa bahasa Indonesia?", eng: "Can you speak Indonesian?" }] },
          { word: "boleh", eng: "may / allowed to", examples: [{ target: "Boleh foto di sini?", eng: "May I take a photo here?" }] },
          { word: "harus", eng: "must / have to", examples: [{ target: "Kamu harus coba ini.", eng: "You have to try this." }] },
          { word: "coba", eng: "try", examples: [{ target: "Coba dulu!", eng: "Try it first!" }] },
          { word: "belajar", eng: "learn / study", examples: [{ target: "Aku lagi belajar bahasa Indonesia.", eng: "I'm studying Indonesian." }] },
          { word: "ajar / mengajar", eng: "teach", examples: [{ target: "Dia ngajar yoga di Ubud.", eng: "She teaches yoga in Ubud." }] },
          { word: "bantu", eng: "help", examples: [{ target: "Bisa bantu aku?", eng: "Can you help me?" }] },
          { word: "pakai", eng: "use / wear", examples: [{ target: "Kamu pakai aplikasi apa?", eng: "What app do you use?" }] },
          { word: "buat", eng: "make / for", examples: [{ target: "Ini buat kamu.", eng: "This is for you." }] },
          { word: "bikin", eng: "make / create", tag: "casual", examples: [{ target: "Aku mau bikin kopi.", eng: "I want to make coffee." }] },
          { word: "kasih", eng: "give", tag: "casual", examples: [{ target: "Kasih aku satu ya.", eng: "Give me one, okay." }] },
          { word: "pinjam", eng: "borrow", examples: [{ target: "Boleh pinjam charger?", eng: "Can I borrow a charger?" }] },
          { word: "mulai", eng: "start / begin", examples: [{ target: "Kelas mulai jam berapa?", eng: "What time does the class start?" }] },
          { word: "selesai", eng: "finish / done", examples: [{ target: "Sudah selesai?", eng: "Are you done?" }] },
          { word: "berhenti", eng: "stop", examples: [{ target: "Berhenti di sini aja.", eng: "Stop here is fine." }] },
          { word: "ganti", eng: "change / replace", examples: [{ target: "Aku mau ganti baju dulu.", eng: "I want to change clothes first." }] },
          { word: "pilih", eng: "choose", examples: [{ target: "Kamu mau pilih yang mana?", eng: "Which one do you want to choose?" }] },
          { word: "ikut", eng: "join / follow / come along", examples: [{ target: "Boleh ikut nggak?", eng: "Can I come along?" }] },
          { word: "duduk", eng: "sit", examples: [{ target: "Duduk di sini aja.", eng: "Just sit here." }] },
          { word: "buka", eng: "open", examples: [{ target: "Toko ini buka jam berapa?", eng: "What time does this shop open?" }] },
          { word: "tutup", eng: "close / closed", examples: [{ target: "Maaf, sudah tutup.", eng: "Sorry, it's already closed." }] },
          { word: "jadi", eng: "become / so (it happened)", examples: [{ target: "Jadi pergi nggak?", eng: "So are we going or not?" }] },
          { word: "ada", eng: "there is / have / exist", examples: [{ target: "Ada WiFi di sini?", eng: "Is there WiFi here?" }] },
          { word: "habis", eng: "run out / used up / after", examples: [{ target: "Airnya sudah habis.", eng: "The water has run out." }] },
          { word: "rusak", eng: "broken / damaged", examples: [{ target: "AC-nya rusak.", eng: "The AC is broken." }] },
          { word: "perbaiki / benerin", eng: "fix / repair", examples: [{ target: "Bisa benerin motor ini?", eng: "Can you fix this motorbike?" }] },
          { word: "tergantung", eng: "depends", examples: [{ target: "Tergantung cuaca.", eng: "Depends on the weather." }] },
          { word: "ketinggalan", eng: "left behind / missed", examples: [{ target: "HP-ku ketinggalan di warung.", eng: "I left my phone at the warung." }] },
          { word: "titip", eng: "leave something with someone / ask someone to get something for you", examples: [{ target: "Kalau ke toko, titip pisang ya.", eng: "If you're going to the store, get me some bananas." }] },
          {
            word: "isi",
            eng: "fill / contents / top up",
            examples: [
              { target: "Aku mau isi bensin dulu.", eng: "I need to fill up gas first." },
              { target: "Isi pulsa dong.", eng: "Top up my phone credit." },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "adjectives",
    title: "Adjective Pairs",
    count: "37 pairs",
    note: "Indonesian adjectives come after the noun: \"air panas\" = water hot (hot water). Learning them as opposite pairs makes them stick faster.",
    subsections: [
      {
        title: "Size & Quantity",
        pairs: [
          { left: { word: "besar", eng: "big" }, right: { word: "kecil", eng: "small" }, examples: [{ target: "Porsinya besar banget.", eng: "The portion is really big." }, { target: "Aku mau yang kecil aja.", eng: "I just want the small one." }] },
          { left: { word: "panjang", eng: "long" }, right: { word: "pendek", eng: "short" }, examples: [{ target: "Jalannya panjang sekali.", eng: "The road is very long." }, { target: "Rambutnya pendek.", eng: "Her/his hair is short." }] },
          { left: { word: "tinggi", eng: "tall / high" }, right: { word: "rendah", eng: "low / short (height)" }, examples: [{ target: "Gunung Agung tinggi banget.", eng: "Mount Agung is really tall." }, { target: "Harganya rendah.", eng: "The price is low." }] },
          { left: { word: "lebar", eng: "wide" }, right: { word: "sempit", eng: "narrow / tight" }, examples: [{ target: "Jalannya lebar.", eng: "The road is wide." }, { target: "Gang ini sempit banget.", eng: "This alley is really narrow." }] },
          { left: { word: "tebal", eng: "thick" }, right: { word: "tipis", eng: "thin" }, examples: [{ target: "Bukunya tebal.", eng: "The book is thick." }, { target: "Rotinya tipis.", eng: "The bread is thin." }] },
          { left: { word: "banyak", eng: "many / much / a lot" }, right: { word: "sedikit", eng: "few / a little" }, examples: [{ target: "Orangnya banyak banget.", eng: "There are so many people." }, { target: "Sedikit aja ya.", eng: "Just a little, okay." }] },
          { left: { word: "penuh", eng: "full" }, right: { word: "kosong", eng: "empty" }, examples: [{ target: "Sudah penuh, nggak bisa masuk.", eng: "It's full, can't get in." }, { target: "Mejanya kosong tuh.", eng: "That table is empty (available)." }] },
        ],
      },
      {
        title: "Quality & State",
        pairs: [
          { left: { word: "bagus", eng: "good / nice" }, right: { word: "jelek", eng: "bad / ugly" }, examples: [{ target: "Tempatnya bagus banget!", eng: "The place is really nice!" }, { target: "Cuacanya jelek hari ini.", eng: "The weather is bad today." }] },
          { left: { word: "enak", eng: "delicious / comfortable" }, right: { word: "nggak enak", eng: "not tasty / uncomfortable" }, examples: [{ target: "Makanannya enak!", eng: "The food is delicious!" }, { target: "Badan aku nggak enak.", eng: "I don't feel well (body uncomfortable)." }] },
          { left: { word: "baru", eng: "new / just (did something)" }, right: { word: "lama", eng: "old (time) / long (duration)" }, examples: [{ target: "Aku baru sampai.", eng: "I just arrived." }, { target: "Sudah lama tinggal di sini?", eng: "Have you lived here long?" }] },
          { left: { word: "mudah / gampang", eng: "easy" }, right: { word: "susah / sulit", eng: "difficult" }, examples: [{ target: "Bahasa Indonesia gampang kok.", eng: "Indonesian is easy, you know." }, { target: "Parkirnya susah di sini.", eng: "Parking is difficult here." }] },
          { left: { word: "bersih", eng: "clean" }, right: { word: "kotor", eng: "dirty" }, examples: [{ target: "Kamarnya bersih.", eng: "The room is clean." }, { target: "Jalannya kotor sesudah hujan.", eng: "The road is dirty after rain." }] },
          { left: { word: "aman", eng: "safe" }, right: { word: "bahaya", eng: "dangerous" }, examples: [{ target: "Di sini aman kok.", eng: "It's safe here, don't worry." }, { target: "Hati-hati, bahaya!", eng: "Be careful, it's dangerous!" }] },
        ],
      },
      {
        title: "Temperature, Weather & Senses",
        pairs: [
          { left: { word: "panas", eng: "hot" }, right: { word: "dingin", eng: "cold" }, examples: [{ target: "Hari ini panas banget.", eng: "Today is really hot." }, { target: "Air dingin, ya.", eng: "Cold water, please." }] },
          { left: { word: "basah", eng: "wet" }, right: { word: "kering", eng: "dry" }, examples: [{ target: "Bajunya masih basah.", eng: "The clothes are still wet." }, { target: "Musim kering sekarang.", eng: "It's dry season now." }] },
          { left: { word: "terang", eng: "bright / light" }, right: { word: "gelap", eng: "dark" }, examples: [{ target: "Kamarnya terang.", eng: "The room is bright." }, { target: "Jalannya gelap malam-malam.", eng: "The road is dark at night." }] },
          { left: { word: "keras", eng: "hard / loud" }, right: { word: "lembut / pelan", eng: "soft / quiet" }, examples: [{ target: "Musiknya keras banget.", eng: "The music is really loud." }, { target: "Bicara pelan-pelan dong.", eng: "Speak softly, please." }] },
          { left: { word: "pedas", eng: "spicy" }, right: { word: "nggak pedas", eng: "not spicy" }, examples: [{ target: "Ini pedas nggak?", eng: "Is this spicy?" }, { target: "Nggak pedas ya, makasih.", eng: "Not spicy, please, thanks." }] },
          { left: { word: "manis", eng: "sweet" }, right: { word: "pahit", eng: "bitter" }, examples: [{ target: "Teh manis, ya.", eng: "Sweet tea, please." }, { target: "Kopinya pahit.", eng: "The coffee is bitter." }] },
          { left: { word: "asin", eng: "salty" }, right: { word: "tawar", eng: "bland / plain" }, examples: [{ target: "Ini terlalu asin.", eng: "This is too salty." }, { target: "Rasanya tawar.", eng: "It tastes bland." }] },
        ],
      },
      {
        title: "Time & Speed",
        pairs: [
          { left: { word: "cepat / cepet", eng: "fast / quick" }, right: { word: "lambat / pelan", eng: "slow" }, examples: [{ target: "WiFi-nya cepat di sini.", eng: "The WiFi is fast here." }, { target: "Pelan-pelan aja.", eng: "Just take it slow / go slowly." }] },
          { left: { word: "awal / pagi", eng: "early" }, right: { word: "telat / terlambat", eng: "late" }, examples: [{ target: "Kamu datang pagi banget.", eng: "You came really early." }, { target: "Maaf, aku telat.", eng: "Sorry, I'm late." }] },
        ],
      },
      {
        title: "Open / Closed & Distance",
        pairs: [
          { left: { word: "buka", eng: "open" }, right: { word: "tutup", eng: "closed" }, examples: [{ target: "Masih buka nggak?", eng: "Is it still open?" }, { target: "Sudah tutup dari jam 9.", eng: "It's been closed since 9." }] },
          { left: { word: "dekat", eng: "near / close" }, right: { word: "jauh", eng: "far" }, examples: [{ target: "Pantainya dekat dari sini.", eng: "The beach is close from here." }, { target: "Jauh nggak?", eng: "Is it far?" }] },
        ],
      },
      {
        title: "Cost & Age",
        pairs: [
          { left: { word: "mahal", eng: "expensive" }, right: { word: "murah", eng: "cheap" }, examples: [{ target: "Kok mahal banget?", eng: "Why is it so expensive?" }, { target: "Di sini lebih murah.", eng: "It's cheaper here." }] },
          { left: { word: "muda", eng: "young" }, right: { word: "tua", eng: "old (age)" }, examples: [{ target: "Dia masih muda.", eng: "He/she is still young." }, { target: "Pohonnya sudah tua.", eng: "The tree is already old." }] },
        ],
      },
      {
        title: "Feelings & People",
        pairs: [
          { left: { word: "senang", eng: "happy / glad" }, right: { word: "sedih", eng: "sad" }, examples: [{ target: "Aku senang tinggal di Bali.", eng: "I'm happy living in Bali." }, { target: "Dia sedih karena temannya pulang.", eng: "She's sad because her friend went home." }] },
          { left: { word: "sibuk", eng: "busy" }, right: { word: "santai / senggang", eng: "relaxed / free" }, examples: [{ target: "Aku lagi sibuk minggu ini.", eng: "I'm busy this week." }, { target: "Santai aja hari ini.", eng: "Just relax today." }] },
          { left: { word: "capek / capai", eng: "tired" }, right: { word: "segar", eng: "fresh / refreshed" }, examples: [{ target: "Aku capek banget hari ini.", eng: "I'm really tired today." }, { target: "Sesudah mandi, badan segar.", eng: "After a shower, I feel refreshed." }] },
          { left: { word: "lapar", eng: "hungry" }, right: { word: "kenyang", eng: "full (stomach)" }, examples: [{ target: "Aku lapar banget.", eng: "I'm really hungry." }, { target: "Sudah kenyang, makasih.", eng: "I'm full already, thanks." }] },
          { left: { word: "haus", eng: "thirsty" }, right: { word: "\u2014", eng: "(no common opposite)" }, examples: [{ target: "Aku haus, mau minum dulu.", eng: "I'm thirsty, I want to drink first." }, { target: "", eng: "" }] },
          { left: { word: "ramai", eng: "crowded / lively" }, right: { word: "sepi", eng: "quiet / empty (of people)" }, examples: [{ target: "Kuta ramai banget.", eng: "Kuta is really crowded." }, { target: "Pantai ini sepi, enak.", eng: "This beach is quiet, nice." }] },
          { left: { word: "benar / betul", eng: "correct / right" }, right: { word: "salah", eng: "wrong / incorrect" }, examples: [{ target: "Betul, itu benar.", eng: "Correct, that's right." }, { target: "Maaf, aku salah.", eng: "Sorry, I was wrong." }] },
          { left: { word: "sama", eng: "same" }, right: { word: "beda", eng: "different" }, examples: [{ target: "Kita sama-sama suka kopi.", eng: "We both like coffee." }, { target: "Rasanya beda.", eng: "The taste is different." }] },
          { left: { word: "kuat", eng: "strong" }, right: { word: "lemah", eng: "weak" }, examples: [{ target: "Kopinya kuat banget.", eng: "The coffee is really strong." }, { target: "Badan aku masih lemah sesudah sakit.", eng: "My body is still weak after being sick." }] },
          { left: { word: "berat", eng: "heavy" }, right: { word: "ringan", eng: "light" }, examples: [{ target: "Tasnya berat banget, isinya apa sih?", eng: "The bag is so heavy, what's inside it?" }, { target: "Kamu ringan banget. Aku bisa gendong kamu.", eng: "You're very light. I can carry you." }] },
        ],
      },
    ],
  },
  {
    id: "connectors",
    title: "Connection Words",
    count: "30 words",
    note: "These are the glue that lets you build real sentences instead of just noun-verb fragments.",
    subsections: [
      {
        title: "Joining & Contrasting",
        words: [
          { word: "dan", eng: "and", examples: [{ target: "Aku mau kopi dan roti.", eng: "I want coffee and bread." }] },
          { word: "sama", eng: "and / with", tag: "casual", examples: [{ target: "Aku pergi sama Jessica.", eng: "I'm going with Jessica." }] },
          { word: "atau", eng: "or", examples: [{ target: "Mau teh atau kopi?", eng: "Do you want tea or coffee?" }] },
          { word: "tapi", eng: "but", examples: [{ target: "Aku mau, tapi nggak bisa.", eng: "I want to, but I can't." }] },
          { word: "cuma / hanya", eng: "only / just", examples: [{ target: "Aku cuma mau tanya satu hal.", eng: "I just want to ask one thing." }] },
          { word: "juga", eng: "also / too", examples: [{ target: "Aku juga mau ikut.", eng: "I also want to come along." }] },
        ],
      },
      {
        title: "Sequence & Time",
        words: [
          { word: "terus / lalu", eng: "then / and then", examples: [{ target: "Makan dulu, terus pergi.", eng: "Eat first, then go." }] },
          { word: "dulu", eng: "first (before doing something else)", examples: [{ target: "Aku mandi dulu ya.", eng: "I'll shower first, okay." }] },
          { word: "sebelum", eng: "before", examples: [{ target: "Sebelum ke pantai, kita makan.", eng: "Before going to the beach, we'll eat." }] },
          { word: "sesudah / setelah", eng: "after", examples: [{ target: "Sesudah makan, aku mau tidur.", eng: "After eating, I want to sleep." }] },
          { word: "sambil", eng: "while (doing something at the same time)", examples: [{ target: "Aku kerja sambil minum kopi.", eng: "I work while drinking coffee." }] },
          { word: "selama", eng: "during / for (a duration)", examples: [{ target: "Aku di Bali selama dua minggu.", eng: "I'm in Bali for two weeks." }] },
          { word: "sampai", eng: "until / up to", examples: [{ target: "Dari jam 8 sampai jam 5.", eng: "From 8 until 5." }] },
          { word: "sejak", eng: "since", examples: [{ target: "Aku tinggal di sini sejak tahun lalu.", eng: "I've lived here since last year." }] },
        ],
      },
      {
        title: "Cause & Condition",
        words: [
          { word: "karena", eng: "because", examples: [{ target: "Aku telat karena macet.", eng: "I'm late because of traffic." }] },
          { word: "jadi", eng: "so / therefore", examples: [{ target: "Hujan, jadi aku di rumah aja.", eng: "It's raining, so I'm just staying home." }] },
          { word: "kalau", eng: "if / when (conditional)", examples: [{ target: "Kalau hujan, kita nggak pergi.", eng: "If it rains, we won't go." }] },
          { word: "supaya / biar", eng: "so that / in order to", examples: [{ target: "Aku belajar supaya bisa ngomong.", eng: "I study so that I can speak." }] },
          { word: "walaupun / meskipun", eng: "although / even though", examples: [{ target: "Walaupun hujan, dia tetap pergi.", eng: "Even though it rained, he still went." }] },
          { word: "untuk / buat", eng: "for / in order to", examples: [{ target: "Ini untuk kamu.", eng: "This is for you." }] },
        ],
      },
      {
        title: "Comparison & Degree",
        words: [
          { word: "lebih", eng: "more / -er (comparative)", examples: [{ target: "Yang ini lebih murah.", eng: "This one is cheaper." }] },
          { word: "paling", eng: "most / -est (superlative)", examples: [{ target: "Ini paling enak.", eng: "This is the most delicious." }] },
          { word: "daripada", eng: "than (in comparisons)", examples: [{ target: "Ubud lebih sejuk daripada Kuta.", eng: "Ubud is cooler than Kuta." }] },
          { word: "seperti / kayak", eng: "like / as / similar to", examples: [{ target: "Dia kayak orang lokal.", eng: "He's like a local person." }] },
          { word: "banget", eng: "very / really (intensifier)", tag: "casual", examples: [{ target: "Enak banget!", eng: "So delicious!" }] },
          { word: "sekali", eng: "very (after adjective)", examples: [{ target: "Bagus sekali!", eng: "Very good!" }] },
          { word: "terlalu", eng: "too (excessive)", examples: [{ target: "Terlalu mahal.", eng: "Too expensive." }] },
          { word: "agak", eng: "somewhat / a bit", examples: [{ target: "Agak jauh sih.", eng: "It's a bit far, to be honest." }] },
          { word: "cukup", eng: "enough / fairly", examples: [{ target: "Sudah cukup, makasih.", eng: "That's enough, thanks." }] },
          { word: "malah", eng: "instead / on the contrary", examples: [{ target: "Bukannya lebih murah, malah lebih mahal.", eng: "Instead of being cheaper, it's actually more expensive." }] },
        ],
      },
    ],
  },
  {
    id: "questions",
    title: "Question Words",
    count: "10 words",
    note: "In spoken Indonesian, question words can go at the beginning or end of the sentence. \"Kamu dari mana?\" and \"Dari mana kamu?\" are both fine.",
    words: [
      { word: "apa", eng: "what", examples: [{ target: "Ini apa?", eng: "What is this?" }] },
      { word: "siapa", eng: "who", examples: [{ target: "Siapa nama kamu?", eng: "What's your name? (lit: Who is your name?)" }] },
      { word: "di mana", eng: "where (location)", examples: [{ target: "Toiletnya di mana?", eng: "Where is the toilet?" }] },
      { word: "ke mana", eng: "where (destination)", examples: [{ target: "Mau ke mana?", eng: "Where are you going?" }] },
      { word: "dari mana", eng: "where from", examples: [{ target: "Kamu dari mana?", eng: "Where are you from?" }] },
      { word: "kapan", eng: "when", examples: [{ target: "Kapan kamu datang?", eng: "When did you arrive?" }] },
      { word: "kenapa / mengapa", eng: "why", examples: [{ target: "Kenapa nggak datang kemarin?", eng: "Why didn't you come yesterday?" }] },
      { word: "bagaimana / gimana", eng: "how", examples: [{ target: "Gimana caranya ke sana?", eng: "How do you get there?" }] },
      { word: "berapa", eng: "how many / how much", examples: [{ target: "Berapa harganya?", eng: "How much does it cost?" }] },
      { word: "yang mana", eng: "which one", examples: [{ target: "Yang mana punyamu?", eng: "Which one is yours?" }] },
    ],
  },
  {
    id: "prepositions",
    title: "Prepositions & Location Words",
    count: "18 words",
    note: "These are essential for giving directions, describing where things are, and talking about time — you'll use them constantly in Bali.",
    words: [
      { word: "di", eng: "at / in (location)", examples: [{ target: "Aku di rumah.", eng: "I'm at home." }] },
      { word: "ke", eng: "to (direction)", examples: [{ target: "Aku mau ke Ubud.", eng: "I want to go to Ubud." }] },
      { word: "dari", eng: "from", examples: [{ target: "Aku dari Romania.", eng: "I'm from Romania." }] },
      { word: "di atas", eng: "on top of / above", examples: [{ target: "Kuncinya di atas meja.", eng: "The key is on the table." }] },
      { word: "di bawah", eng: "under / below", examples: [{ target: "Kucing di bawah kursi.", eng: "The cat is under the chair." }] },
      { word: "di depan", eng: "in front of", examples: [{ target: "Aku tunggu di depan cafe.", eng: "I'll wait in front of the cafe." }] },
      { word: "di belakang", eng: "behind", examples: [{ target: "Parkirnya di belakang.", eng: "The parking is in the back." }] },
      { word: "di samping / di sebelah", eng: "beside / next to", examples: [{ target: "Minimarket di sebelah warung.", eng: "The minimarket is next to the warung." }] },
      { word: "di dalam", eng: "inside", examples: [{ target: "Dompet di dalam tas.", eng: "The wallet is inside the bag." }] },
      { word: "di luar", eng: "outside", examples: [{ target: "Kita duduk di luar aja.", eng: "Let's sit outside." }] },
      { word: "di antara", eng: "between", examples: [{ target: "Canggu di antara Seminyak dan Tanah Lot.", eng: "Canggu is between Seminyak and Tanah Lot." }] },
      { word: "dekat", eng: "near", examples: [{ target: "Dekat pantai.", eng: "Near the beach." }] },
      { word: "lewat", eng: "via / past / through", examples: [{ target: "Lewat jalan ini lebih cepat.", eng: "Going through this road is faster." }] },
      { word: "tentang / soal", eng: "about", examples: [{ target: "Kita ngomong soal rencana besok.", eng: "We're talking about tomorrow's plan." }] },
      { word: "dengan / sama", eng: "with", examples: [{ target: "Aku pergi sama teman.", eng: "I'm going with a friend." }] },
      { word: "tanpa", eng: "without", examples: [{ target: "Kopi tanpa gula.", eng: "Coffee without sugar." }] },
      { word: "kanan", eng: "right", examples: [{ target: "Belok kanan di perempatan.", eng: "Turn right at the intersection." }] },
      { word: "kiri", eng: "left", examples: [{ target: "Toko di sebelah kiri.", eng: "The shop is on the left side." }] },
    ],
  },
  {
    id: "adverbs",
    title: "Time & Frequency Adverbs",
    count: "33 words",
    note: "These are the words that let you talk about when things happen — past, present, future, and how often.",
    subsections: [
      {
        title: "Now, Past & Future",
        words: [
          { word: "sekarang", eng: "now", examples: [{ target: "Kita pergi sekarang.", eng: "We're going now." }] },
          { word: "lagi", eng: "currently / in the process of", examples: [{ target: "Aku lagi makan.", eng: "I'm eating (right now)." }] },
          { word: "sudah / udah", eng: "already (past marker)", examples: [{ target: "Aku udah makan.", eng: "I already ate." }] },
          { word: "belum", eng: "not yet", examples: [{ target: "Belum siap.", eng: "Not ready yet." }] },
          { word: "akan", eng: "will (future marker)", examples: [{ target: "Aku akan datang besok.", eng: "I will come tomorrow." }] },
          { word: "baru", eng: "just (did something recently)", examples: [{ target: "Aku baru sampai.", eng: "I just arrived." }] },
          { word: "masih", eng: "still", examples: [{ target: "Masih hujan nggak?", eng: "Is it still raining?" }] },
          { word: "nanti", eng: "later", examples: [{ target: "Nanti aku kabari ya.", eng: "I'll let you know later, okay." }] },
          { word: "tadi", eng: "earlier today / just now", examples: [{ target: "Tadi aku lihat dia di cafe.", eng: "I saw him/her at the cafe earlier." }] },
          { word: "kemarin", eng: "yesterday", examples: [{ target: "Kemarin hujan deras banget.", eng: "Yesterday it rained really hard." }] },
          { word: "besok", eng: "tomorrow", examples: [{ target: "Besok kita latihan ya.", eng: "Tomorrow we'll practice, okay." }] },
          { word: "lusa", eng: "the day after tomorrow", examples: [{ target: "Lusa aku pergi ke Ubud.", eng: "The day after tomorrow I'm going to Ubud." }] },
        ],
      },
      {
        title: "Frequency",
        words: [
          { word: "selalu", eng: "always", examples: [{ target: "Dia selalu telat.", eng: "He/she is always late." }] },
          { word: "sering", eng: "often", examples: [{ target: "Kamu sering ke sini?", eng: "Do you come here often?" }] },
          { word: "kadang-kadang", eng: "sometimes", examples: [{ target: "Kadang-kadang aku masak sendiri.", eng: "Sometimes I cook by myself." }] },
          { word: "jarang", eng: "rarely / seldom", examples: [{ target: "Aku jarang makan daging.", eng: "I rarely eat meat." }] },
          { word: "nggak pernah", eng: "never", examples: [{ target: "Aku nggak pernah ke Nusa Penida.", eng: "I've never been to Nusa Penida." }] },
          { word: "setiap", eng: "every", examples: [{ target: "Aku latihan setiap pagi.", eng: "I practice every morning." }] },
        ],
      },
      {
        title: "Other Useful Adverbs",
        words: [
          { word: "mungkin", eng: "maybe / possibly", examples: [{ target: "Mungkin besok aku bisa.", eng: "Maybe I can tomorrow." }] },
          { word: "pasti", eng: "definitely / certainly", examples: [{ target: "Pasti enak.", eng: "Definitely delicious." }] },
          { word: "biasanya", eng: "usually", examples: [{ target: "Biasanya aku bangun jam 6.", eng: "Usually I wake up at 6." }] },
          { word: "sebenarnya", eng: "actually / to be honest", examples: [{ target: "Sebenarnya aku nggak suka pedas.", eng: "Actually, I don't like spicy food." }] },
          { word: "memang", eng: "indeed / it's true that", examples: [{ target: "Memang enak di sini.", eng: "It really is nice here." }] },
          { word: "hampir", eng: "almost", examples: [{ target: "Hampir sampai.", eng: "Almost there." }] },
          { word: "kira-kira", eng: "approximately / about", examples: [{ target: "Kira-kira 30 menit dari sini.", eng: "About 30 minutes from here." }] },
          { word: "bareng", eng: "together", examples: [{ target: "Kita pergi bareng ya.", eng: "Let's go together." }] },
          { word: "pisah", eng: "separate / separately", examples: [{ target: "Bayar pisah ya.", eng: "We'll pay separately." }] },
          { word: "sendiri", eng: "alone / by oneself", examples: [{ target: "Aku pergi sendiri.", eng: "I'm going alone." }] },
          { word: "lain", eng: "other / different", examples: [{ target: "Ada warna lain?", eng: "Is there another color?" }] },
          { word: "semua", eng: "all / everything", examples: [{ target: "Semua sudah siap.", eng: "Everything is ready." }] },
          { word: "lancar", eng: "smooth / fluent", examples: [{ target: "Bahasa Indonesianya lancar banget!", eng: "Your Indonesian is so fluent!" }] },
          { word: "bosan", eng: "bored", examples: [{ target: "Aku bosan di rumah terus.", eng: "I'm bored being home all the time." }] },
          { word: "sengaja", eng: "on purpose", examples: [{ target: "Aku nggak sengaja.", eng: "I didn't do it on purpose." }] },
        ],
      },
    ],
  },
  {
    id: "particles",
    title: "Discourse Particles",
    count: "12 words",
    note: "These tiny words are the secret sauce of natural Indonesian. They don't translate cleanly into English — they carry tone, attitude, and social nuance. You'll hear them in literally every sentence spoken around you. Learn to feel them more than define them.",
    words: [
      {
        word: "sih",
        eng: "softener / \"well\u2026\" / mild emphasis",
        tag: "very common",
        examples: [
          { target: "Apa sih?", eng: "What is it? (slightly annoyed or curious)" },
          { target: "Enak sih, tapi mahal.", eng: "It's good, sure, but expensive." },
        ],
      },
      {
        word: "dong",
        eng: "urging / \"come on\" / of course",
        examples: [
          { target: "Bantu dong!", eng: "Help me, come on!" },
          { target: "Iya dong.", eng: "Of course! / Obviously yes." },
        ],
      },
      {
        word: "kok",
        eng: "surprise / \"how come\" / mild challenge",
        examples: [
          { target: "Kok mahal banget?", eng: "How come it's so expensive?" },
          { target: "Enak kok.", eng: "It's good, actually. (reassuring)" },
        ],
      },
      {
        word: "deh",
        eng: "concession / \"fine\" / mild persuasion",
        examples: [
          { target: "Iya deh, aku ikut.", eng: "Fine, I'll come along." },
          { target: "Coba deh.", eng: "Just try it. (encouraging)" },
        ],
      },
      {
        word: "lho / loh",
        eng: "surprise / \"wait, what?\" / alerting",
        examples: [
          { target: "Lho, kamu belum tahu?", eng: "Wait, you didn't know?" },
          { target: "Loh, kok bisa?", eng: "Huh, how is that possible?" },
        ],
      },
      {
        word: "ya",
        eng: "right? / okay? / tag question",
        tag: "very common",
        examples: [
          { target: "Kita ketemu jam 3 ya.", eng: "We'll meet at 3, okay." },
          { target: "Bagus ya tempatnya.", eng: "The place is nice, isn't it." },
        ],
      },
      {
        word: "kan",
        eng: "\"right?\" / seeking agreement / \"as you know\"",
        examples: [
          { target: "Aku kan sudah bilang.", eng: "I already told you, right. (I did say so)" },
          { target: "Enak kan?", eng: "It's good, right?" },
        ],
      },
      {
        word: "nih",
        eng: "\"here\" / drawing attention / this one right here",
        examples: [
          { target: "Nih, coba lihat.", eng: "Here, take a look at this." },
          { target: "Aku capek nih.", eng: "I'm tired, you know. (right now)" },
        ],
      },
      {
        word: "tuh",
        eng: "\"there\" / pointing out / \"see?\"",
        examples: [
          { target: "Tuh kan, aku bilang juga apa.", eng: "See? I told you so." },
          { target: "Dia tuh selalu telat.", eng: "That guy, he's always late." },
        ],
      },
      {
        word: "aja / saja",
        eng: "\"just\" / downplaying / simplifying",
        tag: "very common",
        examples: [
          { target: "Di sini aja.", eng: "Just here is fine." },
          { target: "Santai aja.", eng: "Just relax. / Take it easy." },
        ],
      },
      {
        word: "lah",
        eng: "emphasis / filler / \"well then\"",
        examples: [
          { target: "Ya sudahlah.", eng: "Oh well. / Let it go then." },
          { target: "Mana lah aku tahu.", eng: "How would I know!" },
        ],
      },
      {
        word: "nah",
        eng: "\"so\" / \"right then\" / transitioning",
        examples: [
          { target: "Nah, itu dia!", eng: "There it is! / That's exactly it!" },
          { target: "Nah, sekarang kita bisa mulai.", eng: "Right then, now we can start." },
        ],
      },
    ],
  },
  {
    id: "nouns",
    title: "Common Nouns — Bali Life",
    count: "55 words",
    note: "The physical world around you — places, things, people, and the stuff you deal with day to day living in Bali.",
    subsections: [
      {
        title: "Places & Surroundings",
        words: [
          { word: "jalan", eng: "road / street", examples: [{ target: "Jalannya rusak di sini.", eng: "The road is damaged here." }] },
          { word: "gang", eng: "alley / small lane", examples: [{ target: "Rumahku di gang kecil.", eng: "My house is in a small alley." }] },
          { word: "pantai", eng: "beach", examples: [{ target: "Ayo ke pantai.", eng: "Let's go to the beach." }] },
          { word: "sawah", eng: "rice field", examples: [{ target: "View dari sini sawah semua.", eng: "The view from here is all rice fields." }] },
          { word: "pura", eng: "temple (Balinese Hindu)", examples: [{ target: "Ada upacara di pura hari ini.", eng: "There's a ceremony at the temple today." }] },
          { word: "pasar", eng: "market", examples: [{ target: "Aku beli buah di pasar.", eng: "I bought fruit at the market." }] },
          { word: "warung", eng: "small local restaurant / shop", examples: [{ target: "Warung ini paling enak.", eng: "This warung is the best." }] },
          { word: "toko", eng: "shop / store", examples: [{ target: "Toko itu buka sampai jam 10.", eng: "That shop is open until 10." }] },
          { word: "perempatan", eng: "intersection / crossroads", examples: [{ target: "Belok kanan di perempatan.", eng: "Turn right at the intersection." }] },
        ],
      },
      {
        title: "Home & Living",
        words: [
          { word: "rumah", eng: "house / home", examples: [{ target: "Rumahnya di mana?", eng: "Where is your house?" }] },
          { word: "villa", eng: "villa (very common in Bali context)", examples: [{ target: "Aku sewa villa per bulan.", eng: "I rent a villa monthly." }] },
          { word: "kos / kost", eng: "boarding room / rented room", examples: [{ target: "Aku tinggal di kos dekat pantai.", eng: "I live in a rented room near the beach." }] },
          { word: "kamar", eng: "room", examples: [{ target: "Kamarnya ada AC nggak?", eng: "Does the room have AC?" }] },
          { word: "kamar mandi", eng: "bathroom", examples: [{ target: "Kamar mandinya di sebelah mana?", eng: "Which side is the bathroom?" }] },
          { word: "listrik", eng: "electricity", examples: [{ target: "Listriknya mati.", eng: "The electricity is out." }] },
          { word: "air", eng: "water", examples: [{ target: "Airnya nggak jalan.", eng: "The water isn't running." }] },
          { word: "sampah", eng: "trash / garbage", examples: [{ target: "Buang sampah di mana?", eng: "Where do I throw the trash?" }] },
          { word: "kunci", eng: "key / lock", examples: [{ target: "Kuncinya ketinggalan di rumah.", eng: "The key was left at home." }] },
        ],
      },
      {
        title: "Transport",
        words: [
          { word: "motor", eng: "motorbike / scooter", examples: [{ target: "Aku sewa motor dari tetangga.", eng: "I rent a motorbike from the neighbor." }] },
          { word: "mobil", eng: "car", examples: [{ target: "Macet banget, banyak mobil.", eng: "So much traffic, lots of cars." }] },
          { word: "helm", eng: "helmet", examples: [{ target: "Jangan lupa pakai helm.", eng: "Don't forget to wear a helmet." }] },
          { word: "bensin", eng: "gasoline / fuel", examples: [{ target: "Bensinnya hampir habis.", eng: "The fuel is almost empty." }] },
          { word: "macet", eng: "traffic jam / stuck in traffic", examples: [{ target: "Maaf telat, macet parah.", eng: "Sorry I'm late, traffic was terrible." }] },
        ],
      },
      {
        title: "Weather & Nature",
        words: [
          { word: "hujan", eng: "rain", examples: [{ target: "Kayaknya mau hujan.", eng: "Looks like it's going to rain." }] },
          { word: "matahari", eng: "sun", examples: [{ target: "Mataharinya panas banget hari ini.", eng: "The sun is really hot today." }] },
          { word: "angin", eng: "wind", examples: [{ target: "Anginnya kencang di pantai.", eng: "The wind is strong at the beach." }] },
          { word: "ombak", eng: "waves", examples: [{ target: "Ombaknya besar hari ini.", eng: "The waves are big today." }] },
          { word: "nyamuk", eng: "mosquito", examples: [{ target: "Banyak nyamuk malam-malam.", eng: "Lots of mosquitoes at night." }] },
        ],
      },
      {
        title: "People",
        words: [
          { word: "orang", eng: "person / people", examples: [{ target: "Orangnya baik banget.", eng: "The people are really nice." }] },
          { word: "teman", eng: "friend", examples: [{ target: "Dia teman aku dari Canggu.", eng: "He/she is my friend from Canggu." }] },
          { word: "tetangga", eng: "neighbor", examples: [{ target: "Tetangga aku orang Bali asli.", eng: "My neighbor is a native Balinese." }] },
          { word: "tukang", eng: "handyman / worker / \"the __ guy\"", examples: [{ target: "Panggil tukang listrik.", eng: "Call the electrician." }] },
          { word: "bule", eng: "foreigner (Western)", tag: "casual, neutral", examples: [{ target: "Banyak bule di Canggu.", eng: "There are lots of foreigners in Canggu." }] },
        ],
      },
      {
        title: "Everyday Things",
        words: [
          { word: "uang", eng: "money", examples: [{ target: "Aku nggak bawa uang tunai.", eng: "I didn't bring cash." }] },
          { word: "harga", eng: "price", examples: [{ target: "Berapa harganya?", eng: "How much is the price?" }] },
          { word: "dompet", eng: "wallet", examples: [{ target: "Dompet aku ketinggalan.", eng: "I left my wallet behind." }] },
          { word: "tas", eng: "bag", examples: [{ target: "Taruh di dalam tas aja.", eng: "Just put it in the bag." }] },
          { word: "HP / handphone", eng: "phone / mobile", examples: [{ target: "HP-ku lowbat.", eng: "My phone is low battery." }] },
          { word: "baju", eng: "clothes / shirt", examples: [{ target: "Baju ini basah karena hujan.", eng: "These clothes are wet from the rain." }] },
          { word: "payung", eng: "umbrella", examples: [{ target: "Kamu bawa payung?", eng: "Did you bring an umbrella?" }] },
          { word: "obat", eng: "medicine", examples: [{ target: "Aku perlu beli obat di apotek.", eng: "I need to buy medicine at the pharmacy." }] },
        ],
      },
      {
        title: "Food & Drink Basics",
        words: [
          { word: "nasi", eng: "rice (cooked)", examples: [{ target: "Nasi goreng satu ya.", eng: "One fried rice, please." }] },
          { word: "mie / mi", eng: "noodles", examples: [{ target: "Mie goreng tanpa telur.", eng: "Fried noodles without egg." }] },
          { word: "ayam", eng: "chicken", examples: [{ target: "Aku mau nasi sama ayam.", eng: "I want rice with chicken." }] },
          { word: "telur", eng: "egg", examples: [{ target: "Tambah telur, ya.", eng: "Add an egg, please." }] },
          { word: "sayur", eng: "vegetables", examples: [{ target: "Ada sayur apa hari ini?", eng: "What vegetables are there today?" }] },
          { word: "buah", eng: "fruit", examples: [{ target: "Buah mangga lagi musim.", eng: "Mangoes are in season." }] },
          { word: "gula", eng: "sugar", examples: [{ target: "Tanpa gula ya.", eng: "Without sugar, please." }] },
          { word: "es", eng: "ice", examples: [{ target: "Es kopi satu.", eng: "One iced coffee." }] },
        ],
      },
    ],
  },
  {
    id: "transactions",
    title: "Transaction & Situation Phrases",
    count: "30 phrases",
    note: "Complete phrases you can use as-is in daily situations — ordering, paying, getting around, and dealing with villa/household stuff.",
    subsections: [
      {
        title: "Ordering Food & Drinks",
        words: [
          { word: "Pesan [X] satu.", eng: "I'll order one [X].", examples: [{ target: "Pesan nasi campur satu.", eng: "I'll have one mixed rice." }] },
          { word: "Minta [X] ya.", eng: "Can I have [X], please.", examples: [{ target: "Minta air putih ya.", eng: "Can I have plain water, please." }] },
          { word: "Tambah [X].", eng: "Add [X]. / Extra [X].", examples: [{ target: "Tambah nasi bisa?", eng: "Can I get extra rice?" }] },
          { word: "Tanpa [X] ya.", eng: "Without [X], please.", examples: [{ target: "Tanpa sambal ya.", eng: "Without chili sauce, please." }] },
          { word: "Nggak pedas ya.", eng: "Not spicy, please.", examples: [{ target: "Bisa nggak pedas? Sedikit aja.", eng: "Can it be not spicy? Just a little." }] },
          { word: "Sudah, makasih.", eng: "That's all, thanks.", examples: [{ target: "Sudah cukup, makasih ya.", eng: "That's enough, thanks." }] },
        ],
      },
      {
        title: "Paying & Prices",
        words: [
          { word: "Berapa totalnya?", eng: "How much is the total?", examples: [{ target: "Berapa totalnya, Mas?", eng: "How much is the total, sir?" }] },
          { word: "Bisa bayar pakai [X]?", eng: "Can I pay with [X]?", examples: [{ target: "Bisa bayar pakai kartu?", eng: "Can I pay with a card?" }] },
          { word: "Bisa transfer?", eng: "Can I do a bank transfer?", examples: [{ target: "Nggak bawa cash. Bisa transfer?", eng: "I don't have cash. Can I transfer?" }] },
          { word: "Ada diskon?", eng: "Is there a discount?", examples: [{ target: "Kalau sewa sebulan, ada diskon?", eng: "If I rent for a month, is there a discount?" }] },
          { word: "Bisa kurang?", eng: "Can you lower the price?", examples: [{ target: "Bisa kurang sedikit nggak?", eng: "Can you lower it a little?" }] },
        ],
      },
      {
        title: "Getting Around",
        words: [
          { word: "Ke [X] berapa?", eng: "How much to [X]?", examples: [{ target: "Ke Ubud berapa, Pak?", eng: "How much to Ubud, sir?" }] },
          { word: "Berapa lama ke [X]?", eng: "How long to get to [X]?", examples: [{ target: "Berapa lama ke bandara dari sini?", eng: "How long to the airport from here?" }] },
          { word: "Berhenti di sini aja.", eng: "Stop here is fine.", examples: [{ target: "Mas, berhenti di sini aja ya.", eng: "Sir, just stop here, okay." }] },
          { word: "Lewat mana yang paling cepat?", eng: "Which way is fastest?", examples: [{ target: "Ke Sanur lewat mana yang paling cepat?", eng: "What's the fastest way to Sanur?" }] },
          { word: "Lurus terus.", eng: "Go straight ahead.", examples: [{ target: "Lurus terus, nanti belok kiri.", eng: "Go straight, then turn left." }] },
        ],
      },
      {
        title: "Villa & Household",
        words: [
          { word: "AC-nya nggak dingin.", eng: "The AC isn't cold.", examples: [{ target: "Maaf, AC-nya nggak dingin, bisa dicek?", eng: "Sorry, the AC isn't cold, can it be checked?" }] },
          { word: "WiFi-nya mati.", eng: "The WiFi is down.", examples: [{ target: "WiFi-nya mati dari tadi pagi.", eng: "The WiFi has been down since this morning." }] },
          { word: "Airnya nggak keluar.", eng: "The water isn't coming out.", examples: [{ target: "Air di kamar mandi nggak keluar.", eng: "The water in the bathroom isn't coming out." }] },
          { word: "Bisa tolong perbaiki?", eng: "Can you please fix it?", examples: [{ target: "Pintunya rusak, bisa tolong perbaiki?", eng: "The door is broken, can you please fix it?" }] },
          { word: "Kapan bisa selesai?", eng: "When can it be done?", examples: [{ target: "Kalau diperbaiki, kapan bisa selesai?", eng: "If it's fixed, when can it be done?" }] },
        ],
      },
      {
        title: "Grab / Gojek & Delivery",
        words: [
          { word: "Saya di depan [X].", eng: "I'm in front of [X].", examples: [{ target: "Saya di depan minimarket.", eng: "I'm in front of the minimarket." }] },
          { word: "Sudah sampai?", eng: "Have you arrived?", examples: [{ target: "Mas, sudah sampai belum?", eng: "Sir, have you arrived yet?" }] },
          { word: "Bisa jemput di [X]?", eng: "Can you pick me up at [X]?", examples: [{ target: "Bisa jemput di gang sebelah?", eng: "Can you pick me up at the alley next door?" }] },
          { word: "Titip di depan pintu ya.", eng: "Leave it at the door, please.", examples: [{ target: "Nggak usah ketuk, titip di depan pintu aja ya.", eng: "No need to knock, just leave it at the door." }] },
        ],
      },
    ],
  },
  {
    id: "negation",
    title: "Negation Patterns",
    count: "8 words",
    note: "Indonesian has several different ways to say \"no\" and each one works differently. Getting these right is critical — using the wrong negation word is one of the most common mistakes.",
    words: [
      {
        word: "nggak / tidak",
        eng: "not (negates verbs & adjectives)",
        tag: "most common",
        examples: [
          { target: "Aku nggak mau.", eng: "I don't want to." },
          { target: "Nggak enak.", eng: "Not tasty. / Doesn't feel good." },
        ],
      },
      {
        word: "bukan",
        eng: "not (negates nouns — \"it's not a\u2026\")",
        examples: [
          { target: "Ini bukan punya aku.", eng: "This isn't mine. (not my possession)" },
          { target: "Dia bukan orang Bali.", eng: "He's not Balinese." },
        ],
      },
      {
        word: "belum",
        eng: "not yet",
        examples: [
          { target: "Belum siap.", eng: "Not ready yet." },
          { target: "Sudah makan? — Belum.", eng: "Have you eaten? — Not yet." },
        ],
      },
      {
        word: "jangan",
        eng: "don't (prohibition / instruction)",
        examples: [
          { target: "Jangan lupa!", eng: "Don't forget!" },
          { target: "Jangan parkir di sini.", eng: "Don't park here." },
        ],
      },
      { word: "tanpa", eng: "without", examples: [{ target: "Kopi tanpa gula.", eng: "Coffee without sugar." }] },
      { word: "nggak pernah", eng: "never", examples: [{ target: "Aku nggak pernah ke Lombok.", eng: "I've never been to Lombok." }] },
      { word: "nggak ada", eng: "there isn't / don't have", examples: [{ target: "Maaf, nggak ada stok.", eng: "Sorry, it's out of stock." }] },
      { word: "nggak usah", eng: "no need to / don't bother", examples: [{ target: "Nggak usah antar, aku bisa sendiri.", eng: "No need to drop me off, I can manage." }] },
    ],
  },
  {
    id: "affixes",
    title: "Common Verb Affixes",
    count: "6 patterns",
    note: "You don't need to master these now, but recognizing them will help you understand words you overhear. In casual speech, the me- prefix is almost always dropped — but knowing it exists helps you recognize formal/written forms and search a dictionary.",
    words: [
      {
        word: "me- (prefix)",
        eng: "active voice / \"doing\" — dropped in casual speech",
        examples: [
          { target: "menulis \u2192 nulis (casual)", eng: "to write \u2192 \"Aku lagi nulis.\" = I'm writing." },
          { target: "membeli \u2192 beli / mbeli", eng: "to buy \u2192 \"Aku beli di pasar.\" = I bought it at the market." },
        ],
      },
      {
        word: "di- (prefix)",
        eng: "passive voice / \"being done to\"",
        tag: "very common",
        examples: [
          { target: "Motornya lagi diperbaiki.", eng: "The motorbike is being fixed." },
          { target: "Pesanannya sudah dikirim.", eng: "The order has already been sent." },
        ],
      },
      {
        word: "ber- (prefix)",
        eng: "having / doing (intransitive) — states & activities",
        examples: [
          { target: "Dia bisa berbahasa Indonesia.", eng: "She can speak Indonesian." },
          { target: "Aku mau belajar berenang.", eng: "I want to learn to swim." },
        ],
      },
      {
        word: "-kan (suffix)",
        eng: "do something for someone / cause something",
        examples: [
          { target: "Tolong buatkan kopi.", eng: "Please make (me) a coffee." },
          { target: "Carikan yang murah ya.", eng: "Find me a cheap one, okay." },
        ],
      },
      {
        word: "-in (suffix)",
        eng: "same as -kan but casual / spoken",
        tag: "casual",
        examples: [
          { target: "Ambilin dong.", eng: "Get it for me, will you." },
          { target: "Bantuin aku dong.", eng: "Help me out, come on." },
        ],
      },
      {
        word: "ke- -an (circumfix)",
        eng: "experiencing something (often unpleasant/unintentional)",
        examples: [
          { target: "Aku kehujanan.", eng: "I got caught in the rain." },
          { target: "Dia ketiduran di sofa.", eng: "He fell asleep (accidentally) on the sofa." },
        ],
      },
    ],
  },
  {
    id: "fillers",
    title: "Fillers, Reactions & Interjections",
    count: "18 words",
    note: "The stuff that makes you sound like a real human instead of a textbook. Drop these into conversation and people will immediately feel more comfortable speaking Indonesian with you.",
    words: [
      { word: "wah", eng: "wow / oh (impressed or surprised)", examples: [{ target: "Wah, bagus banget!", eng: "Wow, so nice!" }] },
      { word: "aduh", eng: "ouch / oh no / ugh", examples: [{ target: "Aduh, aku lupa.", eng: "Oh no, I forgot." }] },
      { word: "ya ampun", eng: "oh my god / good grief", examples: [{ target: "Ya ampun, mahal banget!", eng: "Oh my god, so expensive!" }] },
      { word: "astaga", eng: "oh my / good heavens", examples: [{ target: "Astaga, aku salah jalan.", eng: "Oh my, I took the wrong road." }] },
      {
        word: "gitu / begitu",
        eng: "like that / so / I see",
        tag: "very common",
        examples: [
          { target: "Oh gitu. Oke oke.", eng: "Oh, I see. Okay okay." },
          { target: "Caranya gitu.", eng: "That's how you do it." },
        ],
      },
      { word: "gini / begini", eng: "like this", examples: [{ target: "Jadi gini ceritanya\u2026", eng: "So here's the story\u2026 / So basically\u2026" }] },
      { word: "emang / memang", eng: "indeed / that's just how it is", examples: [{ target: "Emang gitu di Bali.", eng: "That's just how it is in Bali." }] },
      { word: "masa / masa sih", eng: "no way / seriously? / really?", examples: [{ target: "Masa sih? Aku nggak percaya.", eng: "No way, really? I don't believe it." }] },
      { word: "serius?", eng: "seriously?", examples: [{ target: "Serius? Kapan?", eng: "Seriously? When?" }] },
      { word: "beneran?", eng: "for real? / really?", tag: "casual", examples: [{ target: "Beneran nih? Nggak bohong?", eng: "For real? Not lying?" }] },
      { word: "ya sudah / yasudah / yaudah", eng: "oh well / okay then / never mind", tag: "very common", examples: [{ target: "Yaudah, nggak apa-apa.", eng: "Oh well, it's fine / no worries." }] },
      { word: "nggak apa-apa", eng: "it's okay / no problem / never mind", examples: [{ target: "Maaf ya. — Nggak apa-apa.", eng: "Sorry. — No problem." }] },
      { word: "ayo / ayuk", eng: "let's go / come on", examples: [{ target: "Ayo makan!", eng: "Let's eat!" }] },
      { word: "hah?", eng: "huh? / what? (didn't hear)", examples: [{ target: "Hah? Bilang apa tadi?", eng: "Huh? What did you say?" }] },
      { word: "iya iya", eng: "yeah yeah / okay okay", examples: [{ target: "Iya iya, aku ngerti.", eng: "Yeah yeah, I understand." }] },
      { word: "hmm / mmm", eng: "(thinking) / (acknowledging)", examples: [{ target: "Hmm, gimana ya\u2026", eng: "Hmm, how do I put it\u2026" }] },
      { word: "oke / okeh", eng: "okay", examples: [{ target: "Oke, siap!", eng: "Okay, ready! / Okay, got it!" }] },
      { word: "siap", eng: "ready / got it / roger that", examples: [{ target: "Siap, Bos!", eng: "Got it, Boss! (common casual reply)" }] },
    ],
  },
  {
    id: "health",
    title: "Body & Health",
    count: "25 words",
    note: "Essential for pharmacies, clinics, and describing how you feel — stuff that really matters when you're not feeling great in a tropical climate.",
    subsections: [
      {
        title: "Body Parts",
        words: [
          { word: "kepala", eng: "head", examples: [{ target: "Kepala aku pusing.", eng: "My head is dizzy." }] },
          { word: "perut", eng: "stomach / belly", examples: [{ target: "Perut aku sakit.", eng: "My stomach hurts." }] },
          { word: "punggung", eng: "back (body)", examples: [{ target: "Punggung aku pegal.", eng: "My back is sore/stiff." }] },
          { word: "tangan", eng: "hand / arm", examples: [{ target: "Tangan aku kena luka.", eng: "My hand got a wound." }] },
          { word: "kaki", eng: "foot / leg", examples: [{ target: "Kaki aku bengkak.", eng: "My foot/leg is swollen." }] },
          { word: "mata", eng: "eye", examples: [{ target: "Mata aku merah.", eng: "My eyes are red." }] },
          { word: "kulit", eng: "skin", examples: [{ target: "Kulit aku gatal.", eng: "My skin is itchy." }] },
        ],
      },
      {
        title: "Symptoms & Conditions",
        words: [
          { word: "sakit", eng: "sick / painful / hurts", examples: [{ target: "Aku sakit dari kemarin.", eng: "I've been sick since yesterday." }] },
          { word: "demam", eng: "fever", examples: [{ target: "Aku demam tinggi.", eng: "I have a high fever." }] },
          { word: "pusing", eng: "dizzy / headache", examples: [{ target: "Aku pusing, mungkin kurang minum.", eng: "I'm dizzy, maybe dehydrated." }] },
          { word: "mual", eng: "nauseous", examples: [{ target: "Aku mual dari tadi.", eng: "I've been nauseous since earlier." }] },
          { word: "batuk", eng: "cough", examples: [{ target: "Aku batuk sudah seminggu.", eng: "I've been coughing for a week." }] },
          { word: "pilek", eng: "runny nose / cold", examples: [{ target: "Aku pilek, butuh tisu.", eng: "I have a runny nose, need tissues." }] },
          { word: "diare", eng: "diarrhea", examples: [{ target: "Aku diare, kayaknya salah makan.", eng: "I have diarrhea, I think I ate something bad." }] },
          { word: "alergi", eng: "allergy / allergic", examples: [{ target: "Aku alergi kacang.", eng: "I'm allergic to nuts." }] },
          { word: "gatal", eng: "itchy", examples: [{ target: "Digigit nyamuk, gatal banget.", eng: "Bitten by a mosquito, so itchy." }] },
          { word: "luka", eng: "wound / injury", examples: [{ target: "Ada luka kecil di kaki.", eng: "There's a small wound on my leg." }] },
          { word: "bengkak", eng: "swollen", examples: [{ target: "Lututnya bengkak.", eng: "The knee is swollen." }] },
          { word: "pegal", eng: "sore / achy / stiff (muscles)", examples: [{ target: "Badan pegal semua habis latihan.", eng: "My whole body is sore after training." }] },
        ],
      },
      {
        title: "At the Pharmacy / Clinic",
        words: [
          { word: "apotek", eng: "pharmacy", examples: [{ target: "Ada apotek dekat sini?", eng: "Is there a pharmacy near here?" }] },
          { word: "dokter", eng: "doctor", examples: [{ target: "Aku perlu ke dokter.", eng: "I need to see a doctor." }] },
          { word: "obat", eng: "medicine / medication", examples: [{ target: "Ada obat untuk sakit kepala?", eng: "Is there medicine for headaches?" }] },
          { word: "resep", eng: "prescription", examples: [{ target: "Perlu resep nggak?", eng: "Do I need a prescription?" }] },
          { word: "sembuh", eng: "healed / recovered", examples: [{ target: "Sudah sembuh belum?", eng: "Have you recovered yet?" }] },
          { word: "istirahat", eng: "rest (as medical advice)", examples: [{ target: "Dokter bilang harus istirahat dua hari.", eng: "The doctor said I need to rest for two days." }] },
        ],
      },
    ],
  },
];
